routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/register/influencer', 	['as' => 'register.influencer', 	'uses' => 'RegisterController@influencer']);
Route::get('/register/brand', 		['as' => 'register.brand', 			'uses' => 'RegisterController@brand']);

Route::group(['prefix' => 'backend/', 'as' => 'backend.', 'namespace' => 'Backend\\', 'middleware' => 'auth'], function(){

	Route::get('dashboard', ['as' => 'dashboard', 		'uses' => 'DashboardController@index']);

	//Post Routes
	Route::get('post', 						['as' => 'post', 				'uses' => 'PostController@index']);
	Route::get('post/create', 				['as' => 'post.create', 		'uses' => 'PostController@create']);
	Route::post('post/store', 				['as' => 'post.store', 			'uses' => 'PostController@store']);
	Route::get('post/view/{slug}', 			['as' => 'post.view', 			'uses' => 'PostController@view']);
	Route::get('post/edit/{slug}', 			['as' => 'post.edit', 			'uses' => 'PostController@edit']);
	Route::post('post/update/{slug}', 		['as' => 'post.update', 		'uses' => 'PostController@update']);
	Route::post('post/delete', 				['as' => 'post.delete', 		'uses' => 'PostController@delete']);

	//Category Routes
	Route::get('category', 						['as' => 'category', 				'uses' => 'CategoryController@index']);
	Route::get('category/create', 				['as' => 'category.create', 		'uses' => 'CategoryController@create']);
	Route::post('category/store', 				['as' => 'category.store', 			'uses' => 'CategoryController@store']);
	Route::get('category/view/{slug}', 			['as' => 'category.view', 			'uses' => 'CategoryController@view']);
	Route::get('category/edit/{slug}', 			['as' => 'category.edit', 			'uses' => 'CategoryController@edit']);
	Route::post('category/update/{slug}', 		['as' => 'category.update', 		'uses' => 'CategoryController@update']);
	Route::post('category/delete', 				['as' => 'category.delete', 		'uses' => 'CategoryController@delete']);

});

Route::group(['as' => 'frontend.', 'namespace' => 'Frontend\\'], function(){

	Route::get('/home', 		['as' => 'home', 		'uses' => 'HomeController@index']);

	//Post Routes
	Route::get('jobs', 						['as' => 'job', 				'uses' => 'JobController@index']);
	Route::get('jobs/{slug}', 				['as' => 'job.view', 			'uses' => 'JobController@view']);

	//Category Routes
	/*Route::get('category', 						['as' => 'category', 				'uses' => 'CategoryController@index']);
	Route::get('category/create', 				['as' => 'category.create', 		'uses' => 'CategoryController@create']);
	Route::post('category/store', 				['as' => 'category.store', 			'uses' => 'CategoryController@store']);
	Route::get('category/view/{slug}', 			['as' => 'category.view', 			'uses' => 'CategoryController@view']);
	Route::get('category/edit/{slug}', 			['as' => 'category.edit', 			'uses' => 'CategoryController@edit']);
	Route::post('category/update/{slug}', 		['as' => 'category.update', 		'uses' => 'CategoryController@update']);
	Route::post('category/delete', 				['as' => 'category.delete', 		'uses' => 'CategoryController@delete']);*/

});

resources/views/backend/layouts/includes/message.blade.php
<div class="alert alert-success">
    {{ session()->get('message') }} <div class="pull-right" onclick="$(this).closest('.alert').remove()"><i class="fa fa-close"></i></div>
</div>

resources/views/backend/layouts/includes/primary_breadcrumb.blade.php
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="{{ route('backend.dashboard') }}">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        @if(isset($panel))
        <li>
            <a href="{{ route($base_route) }}">{{ $panel }}</a>
            <i class="fa fa-circle"></i>
        </li>
        @endif
        <!--<li>
            <span>Page Layouts</span>
        </li>-->
    </ul>
    <!--<div class="page-toolbar">
        <div class="btn-group pull-right">
            <button type="button" class="btn green btn-sm btn-outline dropdown-toggle" data-toggle="dropdown"> Actions
                <i class="fa fa-angle-down"></i>
            </button>
            <ul class="dropdown-menu pull-right" role="menu">
                <li>
                    <a href="#">
                        <i class="icon-bell"></i> Action</a>
                </li>
                <li>
                    <a href="#">
                        <i class="icon-shield"></i> Another action</a>
                </li>
                <li>
                    <a href="#">
                        <i class="icon-user"></i> Something else here</a>
                </li>
                <li class="divider"> </li>
                <li>
                    <a href="#">
                        <i class="icon-bag"></i> Separated link</a>
                </li>
            </ul>
        </div>
    </div>-->
</div>
<!-- END PAGE BAR -->

resources/views/backend/layouts/includes/secondary_breadcrumb.blade.php
<!-- BEGIN PAGE TITLE-->
<h1 class="page-title"> @if(isset($panel)){{ $panel }}@endif
    <!--<small>blank page layout</small>-->
</h1>
<!-- END PAGE TITLE-->